Fix step summary

diff --git a/.github/workflows/build-iso-cuda.yml b/.github/workflows/build-iso-cuda.yml
--- a/.github/workflows/build-iso-cuda.yml
+++ b/.github/workflows/build-iso-cuda.yml
@@ -43,8 +43,19 @@ jobs:
             # Build image
             mkarchiso -v -m iso -w /workspace/work -o /workspace/out /workspace
 
-            # Calculate checksums
-            sha256sum out/* >> $GITHUB_STEP_SUMMARY
+      - name: Create summary
+        run: |
+          # Exit on error
+          set -eu
+
+          # Start code block
+          echo "```" >> $GITHUB_STEP_SUMMARY
+
+          # Calculate checksums
+          sha256sum out/* >> $GITHUB_STEP_SUMMARY
+
+          # End code block
+          echo "```" >> $GITHUB_STEP_SUMMARY
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
